<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WSDLSolicitudDeViaje" targetNamespace="http://j2ee.netbeans.org/wsdl/Solicitud_de_viaje/src/WSDLSolicitudDeViaje"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Solicitud_de_viaje/src/WSDLSolicitudDeViaje" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="WSDLSolicitudDeViajeOperationRequest">
        <part name="id" type="xsd:string"/>
        <part name="part2" type="xsd:string"/>
    </message>
    <message name="WSDLSolicitudDeViajeOperationResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="WSDLSolicitudDeViajePortType">
        <operation name="WSDLSolicitudDeViajeOperation">
            <input name="input1" message="tns:WSDLSolicitudDeViajeOperationRequest"/>
            <output name="output1" message="tns:WSDLSolicitudDeViajeOperationResponse"/>
        </operation>
    </portType>
    <binding name="WSDLSolicitudDeViajeBinding" type="tns:WSDLSolicitudDeViajePortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="WSDLSolicitudDeViajeOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/Solicitud_de_viaje/src/WSDLSolicitudDeViaje"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/Solicitud_de_viaje/src/WSDLSolicitudDeViaje"/>
            </output>
        </operation>
    </binding>
    <service name="WSDLSolicitudDeViajeService">
        <port name="WSDLSolicitudDeViajePort" binding="tns:WSDLSolicitudDeViajeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/WSDLSolicitudDeViajeService/WSDLSolicitudDeViajePort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="WSDLSolicitudDeViaje">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="WSDLSolicitudDeViajePortTypeRole" portType="tns:WSDLSolicitudDeViajePortType"/>
    </plnk:partnerLinkType>
</definitions>
